networks:
  lootradar:
    name: lootradar

services:
  postgres:
    image: postgres:16-alpine
    container_name: lootradar-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lootradar_user_dev
      POSTGRES_PASSWORD: sql123
      POSTGRES_DB: lootradar-dev
      PGPORT: 5433
    ports:
      - '5433:5433'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lootradar
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U lootradar_user_dev -d lootradar-dev -p 5433']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.12
    container_name: lootradar-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lootradar.dev
      PGADMIN_DEFAULT_PASSWORD: lootradar
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - lootradar
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
  backend_nm:
  pgadmin_data:
