name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        cd shared && npm install
        cd ../tests && npm install
        cd ../backend && npm install

    - name: Builds
      run: |
        cd shared && npm run build
        cd ../backend && npm run build

    - name: ESLint
      run: |
        cd backend && npm run lint:check
        cd ../tests && npm run lint:check
